import Link from 'next/link'
import Head from 'next/head'
import MemorySimulator from '../src/components/MemorySimulator'
import MemoryAllocationGame from "../src/components/MemoryAllocationGame";
import MemoryAllocationQuestions from "../src/components/MemoryAllocationQuestions";

export default function Module5(){
  return (
    <>
      <Head><title>Module 5 — Memory Management</title></Head>
      <main style={{fontFamily:'Inter, system-ui, Arial', padding:'2rem', maxWidth:900}}>
        <h1>Module 5: Memory Management</h1>
        <h2>1. Introduction to Memory Management</h2>
        <h3>Motivation of Memory Management</h3>
        <p>To optimize system performance, memory must be strategically managed and shared among multiple processes. Key reasons include:</p>
        <ul>
          <li><strong>CPU Sharing &amp; Scheduling:</strong> To implement effective CPU scheduling, several processes must reside in memory simultaneously.</li>
          <li><strong>Performance Optimization:</strong> Sharing memory directly increases the degree of multiprogramming.</li>
          <li><strong>Management Algorithms:</strong> Specialized memory management algorithms are essential to allocate, track, and protect memory spaces cleanly.</li>
        </ul>

        <h3>What is Memory?</h3>
        <p>It consists of a large array of words or bytes, each assigned its own unique physical address. The CPU fetches instructions and data from memory according to the Program Counter (PC), executing code and writing back updated values.</p>

        <h3>The Lifecycle of a Process in Memory</h3>
        <ol>
          <li><strong>Input Queue:</strong> A collection of processes residing on disk waiting to be brought into main memory.</li>
          <li><strong>Process Placement:</strong> A program must be loaded into memory and placed within an active process environment to execute.</li>
          <li><strong>CPU Scheduling:</strong> The CPU Scheduler selects ready processes from memory to execute on the CPU.</li>
          <li><strong>Execution Access:</strong> While executing, the process dynamically accesses instructions and data directly from memory.</li>
          <li><strong>Termination:</strong> When the process finishes, its allocated memory space is declared available for other jobs.</li>
        </ol>

        <h2>2. Address Binding &amp; Processing Stages</h2>
         <p>Addresses in a source program are typically symbolic. Before execution, they must be mapped to physical memory addresses through a multi-step translation chain:</p>
         <div style={{textAlign:'center', margin:'1rem 0'}}>
           <img src="/images/Address Binding stages.png" alt="Address Binding Stages Illustration" style={{maxWidth:'90%', height:'auto', borderRadius:'4px'}} />
         </div>

        <h3>Three Stages of Address Binding</h3>
        <p>Address binding can take place at different operational stages:</p>
        <ul>
          <li><strong>Compile Time:</strong> Compiler generates absolute code. Requires recompilation if starting address changes.</li>
          <li><strong>Load Time:</strong> Compiler generates relocatable code; final binding handled by the loader at load time.</li>
          <li><strong>Execution Time (Run Time):</strong> Binding delayed until runtime; requires hardware support for address maps (e.g., base and limit registers).</li>
        </ul>

        <h2>3. Logical vs. Physical Address Space</h2>
        <p><strong>Logical (Virtual) Address:</strong> An address generated by the CPU. Programs use logical addresses and do not see physical addresses directly.</p>
        <p><strong>Physical Address:</strong> The actual physical memory location recognized by the hardware.</p>

        <h3>Memory-Management Unit (MMU)</h3>
        <p>The MMU translates virtual addresses into physical addresses at runtime.</p>
        <p><strong>Dynamic Relocation Scheme:</strong> The value stored in the relocation register (base register) is dynamically added to every logical address generated by a user process when accessing memory.</p>
        <p>Physical Address (PA) = Logical Address (LA) + Relocation Register (RA)</p>
        <p>Example: If RA = 14000 and LA = 346, then PA = 346 + 14000 = 14346.</p>

        <h2>4. Operational Concepts: Loading, Linking, &amp; Overlays</h2>
        <h3>Dynamic Loading</h3>
        <p>Routines are kept on disk and are not loaded into main memory until explicitly called. Advantage: improves memory utilization because unused code is never loaded.</p>

        <h3>Static vs. Dynamic Linking</h3>
        <p><strong>Static Linking:</strong> Library routines are combined into the program executable, producing duplicate copies in memory.</p>
        <p><strong>Dynamic Linking:</strong> Linking postponed until run-time using stubs; library routines are shared in memory across processes.</p>

        <h3>Overlays</h3>
        <p>Keep only the necessary instructions/data in memory at any time by overwriting inactive modules. Useful when process size exceeds available memory; implemented at program level.</p>

        <h2>5. Swapping</h2>
        <p>A process can be swapped out of main memory to a backing store and brought back later.</p>
        <ul>
          <li><strong>Backing Store:</strong> High-speed disk large enough to hold copies of memory images for users.</li>
          <li><strong>Roll Out / Roll In:</strong> Variant where lower-priority processes are swapped out to run higher-priority jobs.</li>
        </ul>
        <p><strong>Swapping Constraints:</strong> Processes must be idle before swapping; never swap a process with pending I/O unless I/O uses OS buffers.</p>

        <h3>Sample Problem: Swapping Calculations</h3>
        <p>Problem: Assume a user job is 20,000 words, backing store latency is 8 ms, transfer rate is 250,000 words/sec. Compute total swap time out and in.</p>
        <p>Transfer Time = 20,000 / 250,000 = 0.08 s = 80 ms</p>
        <p>One-way Swap Time = Transfer Time + Latency = 80 ms + 8 ms = 88 ms</p>
        <p>Total Swap Time (Out and In) = 88 ms × 2 = 176 ms</p>

        <h2>6. Memory Allocation &amp; Protection Strategies</h2>
        <p>Modern memory is partitioned into:</p>
        <ul>
          <li><strong>Resident OS:</strong> Typically low memory.</li>
          <li><strong>User Processes:</strong> Typically high memory.</li>
        </ul>

        <h3>Hardware Address Protection</h3>
        <p>Use Base (Relocation) register and Limit register to enforce address bounds. If logical address &ge; limit → trap.</p>
        <div style={{textAlign:'center', margin:'1rem 0'}}>
          <img src="/images/Hardware Address Protection diagram.png" alt="Hardware Address Protection Illustration" style={{maxWidth:'80%', height:'auto', borderRadius:'4px'}} />
        </div>

        <h2>7. Contiguous Memory Allocation Schemes</h2>
        <p>Contiguous allocation requires a process to occupy a single continuous block of memory.</p>
        <h3>A. Monoprogramming (Single-Partition Allocation)</h3>
        <p>Only one user process executes at a time; memory divided between OS and single user program.</p>
        <h3>B. Multiprogramming with a Fixed Number of Tasks (MFT)</h3>
        <p>Memory divided into fixed regions; each region holds one process. Loading may use absolute or relocatable translation.</p>
        <h3>C. Multiprogramming with a Variable Number of Tasks (MVT)</h3>
        <p>Memory boundaries are dynamic; OS manages a free-space list of holes and allocates exact-sized blocks, merging adjacent holes when reclaimed.</p>

        <h2>8. Memory Fragmentation &amp; Allocation Policies</h2>
        <p><strong>Internal Fragmentation:</strong> Unused memory inside an allocated partition. <strong>External Fragmentation:</strong> Free memory exists but split into non-contiguous holes.</p>
        <h3>Allocation Policies</h3>
        <ul>
          <li><strong>First Fit:</strong> Allocate first sufficiently large hole found.</li>
          <li><strong>Best Fit:</strong> Allocate smallest hole that fits (scans entire list).</li>
          <li><strong>Worst Fit / Best Available Fit:</strong> Allocate largest hole to leave large remaining block.</li>
        </ul>
        <p>Solutions: <strong>Compaction</strong> (costly) and <strong>Non-contiguous Allocation</strong> (paging).</p>

        <MemorySimulator />

        <h2>9. Paging: Non-Contiguous Memory Management</h2>
        <p>Paging eliminates external fragmentation by dividing logical address space and physical memory into fixed-size pages and frames.</p>
        <h3>Address Translation</h3>
        <p>The logical address is split into Page Number <em>p</em> and Page Offset <em>d</em>. The page table maps <em>p</em> to frame number <em>f</em>, and the physical address is computed as:</p>
        <p><strong>Physical Address (PA) = (Frame Number f × Page Size P) + Page Offset d</strong></p>

        <h3>The Frame Table</h3>
        <p>The OS maintains a Frame Table with one entry per physical frame, tracking allocation and which process/page occupies it.</p>

        <h3>Fragmentation in Paging</h3>
        <p>External fragmentation: eliminated. Internal fragmentation: may occur in the last page if process size isn't a multiple of page size. Example: page size 16 KB, job 30 KB → allocated 32 KB → internal fragmentation 2 KB.</p>
        <h2>Interactive Activity</h2>
        <MemoryAllocationGame />
        <MemoryAllocationQuestions />
        <p><Link href="/">← Back to modules</Link></p>
      </main>
    </>
  )
}
